# Generated by Django 3.0.5 on 2020-11-01 11:11

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audio', models.FileField(upload_to='articles/audio')),
                ('image', models.ImageField(upload_to='articles/image')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=data.models.diary_photo_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.FirebaseUser')),
            ],
        ),
    ]
