# Generated by Django 3.0.5 on 2020-11-18 07:17

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=data.models.diary_photo_path),
        ),
    ]
