# Generated by Django 3.0.5 on 2021-07-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('favourites', models.ManyToManyField(to='reads.Article')),
            ],
        ),
    ]
