# Generated by Django 3.0.5 on 2021-07-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audio', models.FileField(upload_to='articles/audio')),
                ('image', models.ImageField(upload_to='articles/image')),
            ],
        ),
    ]
